# Generated by Django 5.0.2 on 2024-03-14 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0002_table_user"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="product",
            managers=[],
        ),
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="menu/category_images/"
            ),
        ),
    ]
